# docker-compose.yml
version: "3.7"

services:
  symfony:
    build: symfony_config
    container_name: symfony_docker
    ports:
      - "8245:80"
    volumes:
      - ./symfony_config/vhosts:/etc/apache2/sites-enabled
      - ./symfony_project:/var/www/symfony_project
    restart: always
    networks:
      - dev

  db:
    image: mariadb:10.8.2
    container_name: mariadb_docker
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '!ChangeMeLater!'
    networks:
      - dev

  #   Maybe you should change the container's name & the port bind
  phpmyadmin:
    image: phpmyadmin
    container_name: Verbose-chat_Docker
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES:
        anonymous
        cors_origins "*"
    # Uncomment the following line to enable the development mode
#    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "1234:80"
      - "443:443"
#    volumes:
#      - caddy_data:/data
#      - caddy_config:/config

networks:
  dev:

volumes:
  db-data:
#  caddy_data:
#  caddy_config:
